default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: DenverDoge_development

test:
  <<: *default
  database: DenverDoge_test

production:
  <<: *default
  database: denverdoge
  username: root
  password: denverdoge
  host: denverdoge.co5hqpwgtu5w.us-east-1.rds.amazonaws.com
  port: 3306
