class PetSerializer < ActiveModel::Serializer
  belongs_to :source
  attributes :id,
    :batch_id,
    :external_id,
    :url,
    :species,
    :age,
    :gender,
    :size,
    :coat,
    :tags,
    :name,
    :description,
    :image_url,
    :status,
    :breeds_primary,
    :breeds_secondary,
    :breeds_mixed,
    :colors_primary,
    :colors_secondary,
    :colors_tertiary,
    :attributes_activity_level,
    :attributes_spayed_neutered,
    :attributes_house_trained,
    :attributes_declawed,
    :attributes_special_needs,
    :attributes_shots_current,
    :environment_children,
    :environment_dogs,
    :environment_cats
end
